# Generated by Django 4.1.5 on 2023-01-07 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='fornecedor',
            new_name='preco_dos_fornecedores',
        ),
    ]
