# Generated by Django 4.1.5 on 2023-01-07 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='data_de_atualizacao',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='data_de_criacao',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='data_de_atualizacao',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='data_de_criacao',
            field=models.DateField(auto_now_add=True),
        ),
    ]
