# Generated by Django 4.1.5 on 2023-01-07 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedorpreco',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preco_nos_fornecedores', to='estoque.produto'),
        ),
    ]
