# Generated by Django 4.1.5 on 2023-01-07 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_alter_categoria_data_de_atualizacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoDoFornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_custo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.produto')),
            ],
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='produtos',
            field=models.ManyToManyField(related_name='fornecedores', to='estoque.produtodofornecedor'),
        ),
    ]
