# Generated by Django 4.1.5 on 2023-01-22 13:21

from django.db import migrations, models
import estoque.validators


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_alter_endereco_bairro_alter_endereco_cidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='cnpj',
            field=models.CharField(max_length=18, unique=True, validators=[estoque.validators.valida_cnpj]),
        ),
    ]
